version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker build -t alakarte/work-with-us .
      - run: docker push alakarte/work-with-us
      - run: curl ${DEPLOY_URL}

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: yarn lint

workflows:
  version: 2
  common:
    jobs:
       - build
       - deploy:
          filters:
            branches:
              only:
               - master
               - deploy
          requires:
            - build
